=== ethereum-lists/chains/tools/schema/chainSchema.json
{
    "$schema": "http://json-schema.org/schema#",
    "title": "EIP155 Chain Data",
    "type":"object",
    "required": ["name","shortName","chain","chainId","networkId","rpc","faucets","infoURL","nativeCurrency"],
    "properties": {
        "name":{
            "type":"string",
            "description": "Name of the Network"
        },
        "shortName":{
            "type":"string",
            "pattern": "^[A-Za-z0-9-_]{1,64}$"
        },
        "title":{
            "type":"string",
            "description": "Optional title for the Network"
        },
        "chain":{
            "type":"string",
            "description": "Name of the Network"
        },
        "icon":{
            "type":"string",
            "description": "Icon type"
        },
        "rpc":{
            "type":"array",
            "items":{
                "type":"string"
            }
        },
        "faucets":{
            "type":"array",
            "items":{
                "type":"string"
            }
        },
        "features":{
	    "type":"array",
            "items":{
                "type":"object",
                "properties": {
                    "name":{
                        "type":"string",
			"description": "feature name - e.g. EIP155"
                    }
                }
	    }
	},
        "nativeCurrency":{	    
            "type":"object",
            "properties": {
                "name":{
                    "type":"string",
                    "description":"Name of the Native Currency"
                },
                "symbol":{
                    "type":"string",
                    "description":"Symbol of the Native Currency"
                },
                "decimals":{
                    "type":"number",
                    "description":"Decimal points supported"
                }
            }
        },
        "infoURL":{
            "type":"string",
            "description": "infoURL"
        },
        "chainId":{
            "type":"number",
            "description": "Chain ID of the Network"
        },
        "networkId":{
            "type":"number",
            "description": "Network ID of the Network"
        },
        "slip44":{
            "type":"number",
            "description": "Slip44 of the Network"
        },
        "ens":{
            "type":"object",
            "properties": {
                "registry":{
                    "type":"string"
                }
            }
        },
        "explorers":{
            "type":"array",
            "items":{
                "type":"object",
                "properties": {
                    "name":{
                        "type":"string"
                    },
                    "url":{
                        "type":"string"
                    },
                    "standard":{
                        "type":"string",
			"description": "EIP3091 or none"
                    }
                }
            }
        },
        "parent":{
            "type":"object",
            "properties": {
                "type":{
                    "type":"string"
                },
                "chain":{
                    "type":"string"
                },
                "bridges":{
                    "type":"array",
                    "items": {
                        "type":"object",
                        "properties":{
                            "url": {
                                "type":"string"
                            }
                        }
                    }
                }
            }
        },
        "status":{
            "type":"string"
        },
        "redFlags":{
            "type":"array",
            "items":{
                "type":"string",
                "enum": ["reusedChainId"]
            }
           
        }
    },
    "additionalProperties": false
}

=== ethereum-lists/chains/_data/chains/eip155-127823.json
{
  "name": "Etherlink Shadownet Testnet",
  "chain": "Etherlink",
  "icon": "etherlink",
  "chainId": 127823,
  "networkId": 127823,
  "features": [{ "name": "EIP1559" }],
  "infoURL": "https://etherlink.com",
  "shortName": "etlt",
  "nativeCurrency": {
    "name": "tez",
    "symbol": "XTZ",
    "decimals": 18
  },
  "rpc": ["https://node.shadownet.etherlink.com"],
  "faucets": [],
  "explorers": [
    {
      "name": "Etherlink Shadownet Explorer",
      "url": "https://shadownet.explorer.etherlink.com",
      "standard": "EIP3091"
    }
  ]
}

=== ethereum-lists/chains/_data/chains/eip155-454.json
{
  "name": "TSx Testnet",
  "chain": "AVAX",
  "icon": "avax",
  "rpc": ["https://subnets.avax.network/tsx-testnet/mainnet/rpc"],
  "faucets": [],
  "nativeCurrency": {
    "name": "Avalanche",
    "symbol": "AVAX",
    "decimals": 18
  },
  "features": [{ "name": "EIP1559" }],
  "infoURL": "https://github.com/VenomekPL/TSx-Network",
  "shortName": "tsx-testnet",
  "chainId": 454,
  "networkId": 454,
  "status": "incubating",
  "explorers": [
    {
      "name": "Avalanche Subnet Explorer",
      "url": "https://subnets.avax.network/tsx-testnet",
      "standard": "EIP3091"
    }
  ]
}

=== ethereum-lists/chains/_data/chains/eip155-1781.json
{
  "name": "Valygo NFT L1 Testnet",
  "chain": "VALYGO",
  "icon": "valygo",
  "rpc": [
    "https://rpc-testnet.vyoscan.com/ext/bc/3ouHiy31qmBbEY8Bxchz9dwRKx4F2M2v3u9ZJuKFzmmJrt3oe/rpc"
  ],
  "faucets": [
    "https://faucet-testnet.vyoscan.com"
  ],
  "nativeCurrency": {
    "name": "VALYGO",
    "symbol": "VYO",
    "decimals": 18
  },
  "infoURL": "https://valygo.com",
  "shortName": "vyo-nft",
  "chainId": 1781,
  "networkId": 1781,
  "slip44": 1,
  "explorers": [
    {
      "name": "Valygo NFT Explorer",
      "url": "https://nft-explorer.vyoscan.com",
      "standard": "EIP3091"
    }
  ],
  "status": "active"
}

=== ethereum-lists/chains/_data/chains/eip155-7244.json
{
  "name": "ZEUS Testnet",
  "chain": "tZEUS",
  "icon": "zeusicon",
  "rpc": ["https://testnet-rpc.zeuschainscan.io"],
  "nativeCurrency": {
    "name": "The ZEUS Token",
    "symbol": "ZEUSX",
    "decimals": 18
  },
  "infoURL": "https://testnet-explorer.zeuschainscan.io",
  "shortName": "ZEUS-Testnet",
  "chainId": 7244,
  "networkId": 7244,
  "faucets": ["https://faucet.zeuschainscan.io"],
  "explorers": [
    {
      "name": "ZEUS Testnet Explorer",
      "url": "https://testnet-explorer.zeuschainscan.io",
      "icon": "zeusicon",
      "standard": "EIP3091"
    }
  ]
}

=== ethereum-lists/chains/_data/chains/eip155-364.json
{
  "name": "Theta Amber Testnet",
  "chain": "Theta",
  "rpc": ["https://eth-rpc-api-amber.thetatoken.org/rpc"],
  "faucets": [],
  "nativeCurrency": {
    "name": "Theta Fuel",
    "symbol": "TFUEL",
    "decimals": 18
  },
  "infoURL": "https://www.thetatoken.org/",
  "shortName": "theta-amber",
  "chainId": 364,
  "networkId": 364,
  "slip44": 1,
  "explorers": [
    {
      "name": "Theta Amber Testnet Explorer",
      "url": "https://guardian-testnet-amber-explorer.thetatoken.org",
      "standard": "EIP3091"
    }
  ]
}

=== ethereum-lists/chains/_data/chains/eip155-4888.json
{
  "name": "BlackFort Exchange Network Testnet",
  "chain": "BXNT",
  "rpc": ["https://rpc.blackfort.network/testnet/rpc"],
  "faucets": [],
  "nativeCurrency": {
    "name": "BlackFort Testnet Token",
    "symbol": "BXNT",
    "decimals": 18
  },
  "features": [{ "name": "EIP155" }, { "name": "EIP1559" }],
  "infoURL": "https://blackfort.com",
  "shortName": "BXNT",
  "chainId": 4888,
  "networkId": 4888,
  "slip44": 1,
  "icon": "bxn",
  "explorers": [
    {
      "name": "blockscout",
      "url": "https://testnet.blackfortscan.com",
      "icon": "blockscout",
      "standard": "EIP3091"
    }
  ]
}

=== ethereum-lists/chains/_data/chains/eip155-706883.json
{
  "name": "Fidesinnova",
  "chain": "Fidesinnova",
  "rpc": ["https://rpc1.fidesinnova.io"],
  "faucets": [],
  "nativeCurrency": {
    "name": "Fidesinnova",
    "symbol": "FDS",
    "decimals": 18
  },
  "infoURL": "https://fidesinnova.gitbook.io/docs",
  "shortName": "Fidesinnova",
  "chainId": 706883,
  "networkId": 706883,
  "explorers": [
    {
      "name": "Fidesinnova Blockchain Explorer",
      "url": "https://explorer.fidesinnova.io",
      "standard": "none"
    }
  ]
}

=== ethereum-lists/chains/_data/chains/eip155-18881.json
{
  "name": "Ultra EVM Network Testnet",
  "chain": "Ultra",
  "icon": "ultra",
  "rpc": ["https://evm.test.ultra.eosusa.io"],
  "faucets": [],
  "nativeCurrency": {
    "name": "Ultra Token",
    "symbol": "UOS",
    "decimals": 18
  },
  "infoURL": "https://ultra.io/",
  "shortName": "ultra-testnet",
  "chainId": 18881,
  "networkId": 18881,
  "slip44": 1,
  "explorers": [
    {
      "name": "Ultra EVM Testnet Explorer",
      "url": "https://evmexplorer.testnet.ultra.io",
      "standard": "EIP3091"
    }
  ]
}
