=== ethereum-lists/chains/tools/schema/chainSchema.json
{
    "$schema": "http://json-schema.org/schema#",
    "title": "EIP155 Chain Data",
    "type":"object",
    "required": ["name","shortName","chain","chainId","networkId","rpc","faucets","infoURL","nativeCurrency"],
    "properties": {
        "name":{
            "type":"string",
            "description": "Name of the Network"
        },
        "shortName":{
            "type":"string",
            "pattern": "^[A-Za-z0-9-_]{1,64}$"
        },
        "title":{
            "type":"string",
            "description": "Optional title for the Network"
        },
        "chain":{
            "type":"string",
            "description": "Name of the Network"
        },
        "icon":{
            "type":"string",
            "description": "Icon type"
        },
        "rpc":{
            "type":"array",
            "items":{
                "type":"string"
            }
        },
        "faucets":{
            "type":"array",
            "items":{
                "type":"string"
            }
        },
        "features":{
	    "type":"array",
            "items":{
                "type":"object",
                "properties": {
                    "name":{
                        "type":"string",
			"description": "feature name - e.g. EIP155"
                    }
                }
	    }
	},
        "nativeCurrency":{	    
            "type":"object",
            "properties": {
                "name":{
                    "type":"string",
                    "description":"Name of the Native Currency"
                },
                "symbol":{
                    "type":"string",
                    "description":"Symbol of the Native Currency"
                },
                "decimals":{
                    "type":"number",
                    "description":"Decimal points supported"
                }
            }
        },
        "infoURL":{
            "type":"string",
            "description": "infoURL"
        },
        "chainId":{
            "type":"number",
            "description": "Chain ID of the Network"
        },
        "networkId":{
            "type":"number",
            "description": "Network ID of the Network"
        },
        "slip44":{
            "type":"number",
            "description": "Slip44 of the Network"
        },
        "ens":{
            "type":"object",
            "properties": {
                "registry":{
                    "type":"string"
                }
            }
        },
        "explorers":{
            "type":"array",
            "items":{
                "type":"object",
                "properties": {
                    "name":{
                        "type":"string"
                    },
                    "url":{
                        "type":"string"
                    },
                    "standard":{
                        "type":"string",
			"description": "EIP3091 or none"
                    }
                }
            }
        },
        "parent":{
            "type":"object",
            "properties": {
                "type":{
                    "type":"string"
                },
                "chain":{
                    "type":"string"
                },
                "bridges":{
                    "type":"array",
                    "items": {
                        "type":"object",
                        "properties":{
                            "url": {
                                "type":"string"
                            }
                        }
                    }
                }
            }
        },
        "status":{
            "type":"string"
        },
        "redFlags":{
            "type":"array",
            "items":{
                "type":"string",
                "enum": ["reusedChainId"]
            }
           
        }
    },
    "additionalProperties": false
}

=== ethereum-lists/chains/_data/chains/eip155-19077.json
{
  "name": "BlockX Atlantis Testnet",
  "chain": "blockx",
  "rpc": ["https://atlantis-rpc.blockxnet.com/"],
  "faucets": ["https://ping.blockxnet.com/blockx-atlantis-testnet/faucet"],
  "nativeCurrency": {
    "name": "BCX",
    "symbol": "BCX",
    "decimals": 18
  },
  "features": [{ "name": "EIP155" }, { "name": "EIP1559" }],
  "infoURL": "https://www.blockxnet.com/",
  "shortName": "bcx",
  "chainId": 19077,
  "networkId": 19077,
  "explorers": [
    {
      "name": "BlockX EVM Explorer (Blockscout)",
      "url": "https://testnet-explorer.blockxnet.com/",
      "standard": "EIP3091"
    },
    {
      "name": "BlockX Cosmos Explorer (Ping)",
      "url": "https://ping.blockxnet.com/blockx-atlantis-testnet",
      "standard": "none"
    }
  ]
}

=== ethereum-lists/chains/_data/chains/eip155-534352.json
{
  "name": "Scroll",
  "chain": "ETH",
  "status": "active",
  "rpc": [
    "https://rpc.scroll.io",
    "https://rpc.ankr.com/scroll",
    "https://scroll-mainnet.chainstacklabs.com",
    "https://scroll-rpc.publicnode.com",
    "wss://scroll-rpc.publicnode.com",
    "https://scroll-rpc.blockreq.com/v1/rpc/public",
    "https://rpc.swiftnodes.io/rpc/scroll?key=${SWIFTNODES_API_KEY}"
  ],
  "faucets": [],
  "nativeCurrency": {
    "name": "Ether",
    "symbol": "ETH",
    "decimals": 18
  },
  "infoURL": "https://scroll.io",
  "shortName": "scr",
  "chainId": 534352,
  "networkId": 534352,
  "explorers": [
    {
      "name": "Scrollscan",
      "url": "https://scrollscan.com",
      "standard": "EIP3091"
    }
  ],
  "parent": {
    "type": "L2",
    "chain": "eip155-1",
    "bridges": [{ "url": "https://scroll.io/bridge" }]
  }
}

=== ethereum-lists/chains/chains/eip155-3331.json
{
  "name": "ZCore Testnet",
  "chain": "Beach",
  "icon": "zcore",
  "rpc": ["https://rpc-testnet.zcore.cash"],
  "faucets": ["https://faucet.zcore.cash"],
  "nativeCurrency": {
    "name": "ZCore",
    "symbol": "ZCR",
    "decimals": 18
  },
  "infoURL": "https://zcore.cash",
  "shortName": "zcrbeach",
  "chainId": 3331,
  "networkId": 3331
}

=== ethereum-lists/chains/_data/chains/eip155-721529.json
{
  "name": "ERAM Mainnet",
  "chain": "ERAM",
  "icon": "eram",
  "rpc": ["https://mainnet-rpc.eramscan.com"],
  "faucets": [],
  "nativeCurrency": {
    "name": "ERAM",
    "symbol": "ERAM",
    "decimals": 18
  },
  "infoURL": "http://doc.eramscan.com/",
  "shortName": "ERAM",
  "chainId": 721529,
  "networkId": 721529,
  "explorers": [
    {
      "name": "Eramscan",
      "url": "https://eramscan.com",
      "standard": "EIP3091"
    }
  ]
}

=== ethereum-lists/chains/_data/chains/eip155-821.json
{
  "name": "Callisto Testnet Deprecated",
  "chain": "CLO",
  "rpc": [],
  "faucets": [],
  "nativeCurrency": {
    "name": "Callisto Testnet Ether",
    "symbol": "TCLO",
    "decimals": 18
  },
  "infoURL": "https://callisto.network",
  "shortName": "tclo",
  "chainId": 821,
  "networkId": 2,
  "slip44": 1,
  "status": "deprecated"
}

=== ethereum-lists/chains/_data/chains/eip155-39656.json
{
  "name": "PRM Mainnet",
  "chain": "prm",
  "icon": "prmIcon",
  "rpc": ["https://mainnet-rpc.prmscan.org"],
  "faucets": [],
  "nativeCurrency": {
    "name": "Primal Network",
    "symbol": "PRM",
    "decimals": 18
  },
  "infoURL": "https://primalnetwork.org",
  "shortName": "prm",
  "chainId": 39656,
  "networkId": 39656,
  "explorers": [
    {
      "name": "Primal Network",
      "url": "https://prmscan.org",
      "standard": "EIP3091"
    }
  ]
}

=== ethereum-lists/chains/_data/chains/eip155-32520.json
{
  "name": "Bitgert Mainnet",
  "chain": "Brise",
  "rpc": [
    "https://rpc-bitgert.icecreamswap.com",
    "https://mainnet-rpc.brisescan.com",
    "https://chainrpc.com",
    "https://serverrpc.com"
  ],
  "faucets": [],
  "nativeCurrency": {
    "name": "Bitrise Token",
    "symbol": "Brise",
    "decimals": 18
  },
  "infoURL": "https://bitgert.com/",
  "shortName": "Brise",
  "chainId": 32520,
  "networkId": 32520,
  "icon": "brise",
  "explorers": [
    {
      "name": "Brise Scan",
      "url": "https://brisescan.com",
      "icon": "brise",
      "standard": "EIP3091"
    }
  ]
}

=== ethereum-lists/chains/_data/chains/eip155-397.json
{
  "name": "NEAR Protocol",
  "chain": "NEAR",
  "rpc": ["https://eth-rpc.mainnet.near.org"],
  "icon": "near",
  "faucets": [],
  "nativeCurrency": {
    "name": "NEAR",
    "symbol": "NEAR",
    "decimals": 18
  },
  "infoURL": "https://near.org",
  "shortName": "near",
  "chainId": 397,
  "networkId": 397,
  "explorers": [
    {
      "name": "NEAR Explorer",
      "url": "https://eth-explorer.near.org",
      "standard": "EIP3091"
    }
  ]
}
